/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: leslava (https://sketchfab.com/leslava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toy-island-fantasyislandchallenge-1aa836a95e2848008ad255ddf55e5530
Title: Toy Island #FantasyIslandChallenge
*/
import { a } from "@react-spring/three";
import { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import newIslandScene from "../assets/3d/newIsLand.glb";

export function NewIsland({
  isRotating,
  setIsRotating,
  setCurrentStage,
  isDancing,
  setIsDancing,
  currentFocusPoint,
  ...props
}) {
  const newIslandRef = useRef();
  // Get access to the Three.js renderer and viewport
  const { gl, viewport } = useThree();
  const { nodes, materials, animations } = useGLTF(newIslandScene);
  console.log("animations", animations);

  // State for zoom control
  const [zoom, setZoom] = useState(1);
  const minZoom = 0.5;
  const maxZoom = 3;

  // Dance animation ref
  const danceTime = useRef(0);

  // 预识别动画部件，避免每帧遍历检查
  const [partsIdentified, setPartsIdentified] = useState(false);
  useEffect(() => {
    if (newIslandRef.current && !partsIdentified) {
      // 小人模型的位置信息
      const characterPosition = [-64.665, 59.278, -66.443];
      const rodPosition = [-11.851, 36.02, -6.99];

      newIslandRef.current.traverse((child) => {
        if (child.isMesh) {
          // 保存原始位置
          child.userData.originalPosition = {
            x: child.position.x,
            y: child.position.y,
            z: child.position.z,
          };
          child.userData.originalRotation = {
            x: child.rotation.x,
            y: child.rotation.y,
            z: child.rotation.z,
          };

          // 检查是否是小人模型的子对象
          let isCharacterPart = false;
          let current = child;

          // 向上遍历父级链，检查是否属于小人模型
          while (current && current.parent) {
            if (
              current.parent.position &&
              Math.abs(current.parent.position.x - characterPosition[0]) <
                0.1 &&
              Math.abs(current.parent.position.y - characterPosition[1]) <
                0.1 &&
              Math.abs(current.parent.position.z - characterPosition[2]) < 0.1
            ) {
              isCharacterPart = true;
              break;
            }
            current = current.parent;
          }

          if (isCharacterPart) {
            child.userData.isCharacterPart = true;
            // 检查是否是头部部件
            if (
              child.name &&
              (child.name.toLowerCase().includes("head") ||
                child.name.toLowerCase().includes("face") ||
                child.name.toLowerCase().includes("hair") ||
                child.name.toLowerCase().includes("ear") ||
                child.name.toLowerCase().includes("headphones"))
            ) {
              child.userData.isHeadPart = true;
            }
          }
        }
      });

      // 调试：输出找到的部件数量
      let headParts = 0;
      let characterParts = 0;

      newIslandRef.current.traverse((child) => {
        if (child.userData.isHeadPart) headParts++;
        if (child.userData.isCharacterPart) characterParts++;
      });

      setPartsIdentified(true);
    }
  }, [newIslandRef, partsIdentified]);

  // Use a ref for the last mouse x position
  const lastX = useRef(0);
  // Use a ref for rotation speed
  const rotationSpeed = useRef(0);
  // Define a damping factor to control rotation damping
  const dampingFactor = 0.95;

  // Handle pointer (mouse or touch) down event
  const handlePointerDown = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(true);

    // Calculate the clientX based on whether it's a touch event or a mouse event
    const clientX = event.touches ? event.touches[0].clientX : event.clientX;

    // Store the current clientX position for reference
    lastX.current = clientX;
  };

  // Handle pointer (mouse or touch) up event
  const handlePointerUp = (event) => {
    event.stopPropagation();
    event.preventDefault();
    setIsRotating(false);
  };

  // Handle pointer (mouse or touch) move event
  const handlePointerMove = (event) => {
    event.stopPropagation();
    event.preventDefault();
    if (isRotating) {
      // If rotation is enabled, calculate the change in clientX position
      const clientX = event.touches ? event.touches[0].clientX : event.clientX;

      // calculate the change in the horizontal position of the mouse cursor or touch input,
      // relative to the viewport's width
      const delta = (clientX - lastX.current) / viewport.width;

      // Update the island's rotation based on the mouse/touch movement
      newIslandRef.current.rotation.y += delta * 0.01 * Math.PI;

      // Update the reference for the last clientX position
      lastX.current = clientX;

      // Update the rotation speed
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  // Handle keydown events
  const handleKeyDown = (event) => {
    if (event.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);

      newIslandRef.current.rotation.y += 0.005 * Math.PI;
      rotationSpeed.current = 0.007;
    } else if (event.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);

      newIslandRef.current.rotation.y -= 0.005 * Math.PI;
      rotationSpeed.current = -0.007;
    } else if (event.key === " " || event.key === "d" || event.key === "D") {
      // Spacebar or 'D' key to toggle dancing
      setIsDancing && setIsDancing(!isDancing);
    }
  };

  // Handle keyup events
  const handleKeyUp = (event) => {
    if (event.key === "ArrowLeft" || event.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  // Touch events for mobile devices
  const handleTouchStart = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;
    lastX.current = clientX;
  };

  const handleTouchEnd = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handleTouchMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;
      const delta = (clientX - lastX.current) / viewport.width;

      newIslandRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  // Handle mouse wheel for zoom
  const handleWheel = (event) => {
    event.stopPropagation();
    event.preventDefault();

    const delta = event.deltaY > 0 ? -0.1 : 0.1;
    const newZoom = Math.max(minZoom, Math.min(maxZoom, zoom + delta));
    setZoom(newZoom);

    // Apply zoom to scale
    if (newIslandRef.current) {
      const baseScale = Array.isArray(props.scale)
        ? props.scale[0]
        : props.scale || 1;
      newIslandRef.current.scale.set(
        baseScale * newZoom,
        baseScale * newZoom,
        baseScale * newZoom
      );
    }
  };

  useEffect(() => {
    // Add event listeners for pointer and keyboard events
    const canvas = gl.domElement;
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);
    canvas.addEventListener("wheel", handleWheel);
    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("keyup", handleKeyUp);
    canvas.addEventListener("touchstart", handleTouchStart);
    canvas.addEventListener("touchend", handleTouchEnd);
    canvas.addEventListener("touchmove", handleTouchMove);

    // Remove event listeners when component unmounts
    return () => {
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);
      canvas.removeEventListener("wheel", handleWheel);
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("keyup", handleKeyUp);
      canvas.removeEventListener("touchstart", handleTouchStart);
      canvas.removeEventListener("touchend", handleTouchEnd);
      canvas.removeEventListener("touchmove", handleTouchMove);
    };
  }, [
    gl,
    handlePointerDown,
    handlePointerUp,
    handlePointerMove,
    handleWheel,
    handleTouchStart,
    handleTouchEnd,
    handleTouchMove,
  ]);

  // This function is called on each frame update
  useFrame((state, delta) => {
    // Apply current zoom to scale
    if (newIslandRef.current) {
      const baseScale = Array.isArray(props.scale)
        ? props.scale[0]
        : props.scale || 1;
      newIslandRef.current.scale.set(
        baseScale * zoom,
        baseScale * zoom,
        baseScale * zoom
      );
    }

    // If not rotating, apply damping to slow down the rotation (smoothly)
    if (!isRotating) {
      // Apply damping factor
      rotationSpeed.current *= dampingFactor;

      // Stop rotation when speed is very small
      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      newIslandRef.current.rotation.y += rotationSpeed.current;
    } else {
      // When rotating, determine the current stage based on island's orientation
      const rotation = newIslandRef.current.rotation.y;

      /**
       * Normalize the rotation value to ensure it stays within the range [0, 2 * Math.PI].
       * The goal is to ensure that the rotation value remains within a specific range to
       * prevent potential issues with very large or negative rotation values.
       *  Here's a step-by-step explanation of what this code does:
       *  1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided
       *     by 2 * Math.PI. This essentially wraps the rotation value around once it reaches a
       *     full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI.
       *  2. (rotation % (2 * Math.PI)) + 2 * Math.PI adds 2 * Math.PI to the result from step 1.
       *     This is done to ensure that the value remains positive and within the range of
       *     0 to 2 * Math.PI even if it was negative after the modulo operation in step 1.
       *  3. Finally, ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI) applies another
       *     modulo operation to the value obtained in step 2. This step guarantees that the value
       *     always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
       *     circle in radians.
       */
      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }

    // 小人跳舞动画 - 优化版本
    if (isDancing) {
      danceTime.current += delta;

      // 调试：每5秒输出一次动画状态
      if (
        Math.floor(danceTime.current * 0.2) % 1 === 0 &&
        danceTime.current > 0
      ) {
      }

      // 找到小人模型并应用动画
      if (newIslandRef.current) {
        // 预计算动画值，避免重复计算
        const bounceHeight = Math.sin(danceTime.current * 6) * 0.4;
        const sideSway = Math.sin(danceTime.current * 3) * 0.25;
        const rotationZ = Math.sin(danceTime.current * 8) * 0.3;
        const headBob = Math.sin(danceTime.current * 5) * 0.1;
        const headSway = Math.sin(danceTime.current * 4) * 0.1;
        const depthSway = Math.sin(danceTime.current * 4) * 0.05;

        // 小人模型的位置信息
        const characterPosition = [-64.665, 59.278, -66.443];

        let animatedParts = 0;
        let characterAnimatedParts = 0;
        let headAnimatedParts = 0;

        newIslandRef.current.traverse((child) => {
          if (child.userData.isCharacterPart || child.userData.isHeadPart) {
            animatedParts++;
            // 处理角色、头部和小车部件
            if (child.userData.originalPosition) {
              // 应用位置动画
              child.position.x = child.userData.originalPosition.x + sideSway;
              child.position.y =
                child.userData.originalPosition.y + bounceHeight;
              child.position.z = child.userData.originalPosition.z + depthSway;

              // 应用旋转动画
              if (child.rotation && child.userData.originalRotation) {
                if (child.userData.isHeadPart) {
                  headAnimatedParts++;
                  child.position.y += 0.3; // 头部额外抬高
                  child.rotation.x =
                    child.userData.originalRotation.x + headBob;
                  child.rotation.y =
                    child.userData.originalRotation.y + headSway;
                  child.rotation.z =
                    child.userData.originalRotation.z + rotationZ * 1.5;
                } else if (child.userData.isCharacterPart) {
                  characterAnimatedParts++;
                  // 普通角色部分动画
                  child.rotation.x =
                    child.userData.originalRotation.x + headBob;
                  child.rotation.z =
                    child.userData.originalRotation.z + rotationZ;
                }
              }
            }
          }
        });
      }
    } else {
      // 重置位置 - 仅重置需要重置的部分
      if (newIslandRef.current) {
        newIslandRef.current.traverse((child) => {
          if (child.userData.originalPosition) {
            child.position.x = child.userData.originalPosition.x;
            child.position.y = child.userData.originalPosition.y;
            child.position.z = child.userData.originalPosition.z;
          }
          if (child.userData.originalRotation && child.rotation) {
            child.rotation.x = child.userData.originalRotation.x;
            child.rotation.y = child.userData.originalRotation.y;
            child.rotation.z = child.userData.originalRotation.z;
          }
        });
      }
    }
  });

  return (
    <a.group ref={newIslandRef} {...props} dispose={null}>
      <group position={[-76.118, 45.202, 45.122]}>
        {/* 小人模型开始 */}
        <group
          position={[-64.665, 59.278, -66.443]}
          rotation={[0, 1.059, 0]}
          scale={0.1}
        >
          <group
            position={[66.125, 125.074, -172.399]}
            rotation={[0, 0, -0.334]}
          >
            <group
              position={[-31.662, -171.55, 236.649]}
              rotation={[0.021, -0.106, 0.29]}
            >
              <group
                position={[16.18, 49.574, -5.07]}
                rotation={[0.01, 0.108, -0.338]}
              >
                <mesh
                  geometry={nodes.BODY_Mat1_0.geometry}
                  material={materials["Mat.1_0"]}
                />
                <mesh
                  geometry={nodes.BODY__0.geometry}
                  material={materials.BODY__0}
                />
              </group>
              <mesh
                geometry={nodes.Sphere_7_Mat_0.geometry}
                material={materials.Mat_0}
                position={[-0.79, 1.173, -3.659]}
                rotation={[3.102, -0.011, 0.38]}
              />
              <mesh
                geometry={nodes.Sphere_1_Mat_0.geometry}
                material={materials.Mat_0}
                position={[35.643, 102.151, -8.064]}
                rotation={[3.102, -0.011, -2.761]}
              />
            </group>
            <mesh
              geometry={nodes.Sweep_Mat1_0.geometry}
              material={materials["Mat.1"]}
              position={[-39.17, -69.237, 278.606]}
              rotation={[0.016, -0.314, 0.207]}
            />
            <mesh
              geometry={nodes.Cube_Mat_0.geometry}
              material={materials.material}
              position={[-326.439, -616.844, 586.811]}
              rotation={[0.233, 1.092, -0.131]}
            />
            <mesh
              geometry={nodes.Hand_Mat1_0.geometry}
              material={materials["Mat.1"]}
              position={[-23.938, 0, 137.13]}
            />
            <mesh
              geometry={nodes.Cube_1_Mat_0.geometry}
              material={materials.Mat_0}
              position={[-514.965, -669.898, -78.774]}
              rotation={[-0.033, -0.048, 0.794]}
            />
          </group>
          {/* 头部 */}
          <group
            position={[-11.685, 201.28, 64.749]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <group
              position={[-13.463, -75.568, 0.176]}
              rotation={[-0.336, 0.134, -0.616]}
            >
              <mesh
                geometry={nodes.Face_Mat3_0.geometry}
                material={materials["Mat.3"]}
              />
              <mesh
                geometry={nodes.Face_Mat_0.geometry}
                material={materials.Mat_0}
              />
              <mesh
                geometry={nodes.Face_Mat1_0.geometry}
                material={materials["Mat.1_1"]}
              />
              <mesh
                geometry={nodes.Face_Mat_0_1.geometry}
                material={materials.Mat_1}
              />
            </group>
            <group
              position={[-21.208, -68.79, -0.896]}
              rotation={[-0.336, 0.134, -0.452]}
            >
              <mesh
                geometry={nodes.Sphere_7_1_1_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[128.758, -40.306, -55.504]}
                rotation={[0.252, 0.426, -1.675]}
              />
              <mesh
                geometry={nodes.Sphere_7_1_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[134.945, -44.35, 45.017]}
                rotation={[0.057, -0.336, -1.602]}
              />
              <mesh
                geometry={nodes.Headphones_1_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[20.307, -7.354, 3.187]}
                rotation={[-1.573, 0.151, -0.028]}
              />
              <mesh
                geometry={nodes.Tube_2_Mat1_0.geometry}
                material={materials["Mat.1_0"]}
                position={[-88.637, -12.717, -5.611]}
                rotation={[0, 0, 1.642]}
              />
              <mesh
                geometry={nodes.Ear_2_Mat1_0.geometry}
                material={materials["Mat.1_0"]}
                position={[5.104, -4.996, 122.216]}
                rotation={[1.612, -0.003, -0.113]}
              />
              <mesh
                geometry={nodes.Ear_1_Mat1_0.geometry}
                material={materials["Mat.1_0"]}
                position={[6.042, 7.168, -117.156]}
                rotation={[1.612, -0.003, 0.201]}
              />
              <mesh
                geometry={nodes.Cube_2_Mat_0.geometry}
                material={materials.Mat_0}
                position={[60.092, -15.367, 113.49]}
                rotation={[1.582, -0.145, -0.211]}
              />
              <mesh
                geometry={nodes.Ear_inside_Mat_0.geometry}
                material={materials.Mat_0}
                position={[6.013, 7.21, -123.348]}
                rotation={[Math.PI / 2, 0, 0.212]}
              />
              <mesh
                geometry={nodes.Ear_inside_1_Mat_0.geometry}
                material={materials.Mat_0}
                position={[6.215, -3.929, 128.065]}
                rotation={[Math.PI / 2, 0, -0.064]}
              />
              <mesh
                geometry={nodes.Cube_1_2_Mat_0.geometry}
                material={materials.Mat_0}
                position={[57.812, -12.031, -107.261]}
                rotation={[1.707, -0.281, 0.251]}
              />
            </group>
            <group
              position={[9.704, -8.903, 415.645]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <group
                position={[-15.033, 410.766, -71.774]}
                rotation={[-0.401, 0.447, 0.148]}
              >
                <mesh
                  geometry={nodes.Hair_2_Mat_0.geometry}
                  material={materials.material}
                />
                <mesh
                  geometry={nodes.Hair_2_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
              </group>
            </group>
          </group>
          {/* 腿部 */}
          <group
            position={[-54.44, -326.353, 107.651]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <group
              position={[-9.934, -66.464, -106.515]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <group
                position={[-73.728, 115.757, 310.449]}
                rotation={[-0.015, -0.107, -0.046]}
              >
                <mesh
                  geometry={nodes.Sphere_8_Sphere_Mat3_0.geometry}
                  material={materials["Mat.3"]}
                  position={[0.179, 159.091, -309.94]}
                  rotation={[-Math.PI, 0, 1.457]}
                />
              </group>
              <group
                position={[-31.23, 275.272, -10.835]}
                rotation={[2.129, 0.019, 0.293]}
              >
                <mesh
                  geometry={nodes.Tube_2_2_Mat_0.geometry}
                  material={materials.Mat_0}
                  position={[3.644, 16.768, -11.467]}
                  rotation={[-1.138, 0.146, 2.899]}
                />
              </group>
              <group
                position={[-36.579, 193.176, 0.731]}
                rotation={[-0.015, -0.107, -0.046]}
              >
                <mesh
                  geometry={nodes.Cylinder_4_Mat1_0.geometry}
                  material={materials["Mat.1_0"]}
                />
                <mesh
                  geometry={nodes.Cylinder_4_Mat1_0_1.geometry}
                  material={materials["Mat.1_2"]}
                />
              </group>
              <group position={[-39.367, 97.677, 1.318]}>
                <mesh
                  geometry={nodes.Cylinder_2_5_Mat1_0.geometry}
                  material={materials["Mat.1_0"]}
                />
                <mesh
                  geometry={nodes.Cylinder_2_5_Mat1_0_1.geometry}
                  material={materials["Mat.1_2"]}
                />
              </group>
              <mesh
                geometry={nodes.Cube_2_2_Mat_0.geometry}
                material={materials.Mat_0}
                position={[-33.844, 253.462, 0.131]}
                rotation={[-0.015, -0.107, -0.046]}
              />
              <mesh
                geometry={nodes.Cylinder_1_4_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[-39.367, 23.972, 1.318]}
              />
              <mesh
                geometry={nodes.Sphere_1_4_Mat_0.geometry}
                material={materials.material}
                position={[10.636, -51.353, 7.564]}
              />
              <mesh
                geometry={nodes.Cylinder_3_5_Mat1_0.geometry}
                material={materials["Mat.1"]}
                position={[-39.367, -38.534, 1.318]}
              />
            </group>
            <group
              position={[-9.934, -66.464, 14.649]}
              rotation={[0, 0, -Math.PI / 2]}
            >
              <group
                position={[-73.728, 115.757, 310.449]}
                rotation={[-0.015, -0.107, -0.046]}
              >
                <mesh
                  geometry={nodes.Sphere_8_Sphere_2_Mat3_0.geometry}
                  material={materials["Mat.3"]}
                  position={[0, 160.658, -314.905]}
                  rotation={[-Math.PI, 0, 1.457]}
                />
              </group>
              <group
                position={[-31.23, 275.272, -10.835]}
                rotation={[2.129, 0.019, 0.293]}
              >
                <mesh
                  geometry={nodes.Tube_2_4_Mat_0.geometry}
                  material={materials.Mat_0}
                  position={[-1.555, -2.322, -1.043]}
                  rotation={[0.049, -0.005, -0.123]}
                />
              </group>
              <group
                position={[-36.579, 193.176, -2.669]}
                rotation={[-0.015, -0.107, -0.046]}
              >
                <mesh
                  geometry={nodes.Cylinder_4_3_Mat1_0.geometry}
                  material={materials["Mat.1_0"]}
                />
                <mesh
                  geometry={nodes.Cylinder_4_3_Mat1_0_1.geometry}
                  material={materials["Mat.1_2"]}
                />
              </group>
              <group position={[-39.367, 97.677, -2.082]}>
                <mesh
                  geometry={nodes.Cylinder_2_6_Mat1_0.geometry}
                  material={materials["Mat.1_0"]}
                />
                <mesh
                  geometry={nodes.Cylinder_2_6_Mat1_0_1.geometry}
                  material={materials["Mat.1_2"]}
                />
              </group>
              <mesh
                geometry={nodes.Cube_2_3_Mat_0.geometry}
                material={materials.Mat_0}
                position={[-33.844, 253.462, -3.268]}
                rotation={[-0.015, -0.107, -0.046]}
              />
              <mesh
                geometry={nodes.Cylinder_1_5_Mat3_0.geometry}
                material={materials["Mat.3"]}
                position={[-39.367, 23.972, -2.082]}
              />
              <mesh
                geometry={nodes.Sphere_1_5_Mat_0.geometry}
                material={materials.material}
                position={[10.636, -51.353, 4.164]}
              />
              <mesh
                geometry={nodes.Cylinder_3_6_Mat1_0.geometry}
                material={materials["Mat.1"]}
                position={[-39.367, -38.534, -2.082]}
              />
            </group>
          </group>
        </group>
        {/* 小人模型结束 */}
        <group position={[206, 137.086, -45.122]} rotation={[0, 0, Math.PI]}>
          <group position={[10.484, 12.495, 0]} rotation={[0, 0, Math.PI]}>
            <group position={[-0.051, -51.506, 0]}>
              <mesh
                geometry={nodes.Torus_3_Mat1_0.geometry}
                material={materials["Mat.1_3"]}
              />
              <mesh
                geometry={nodes.Torus_3_Mat1_0_1.geometry}
                material={materials["Mat.1_4"]}
              />
              <mesh
                geometry={nodes.Torus_3_Mat1_0_2.geometry}
                material={materials["Mat.1_5"]}
              />
            </group>
            <group position={[-0.051, -24.81, 0]}>
              <mesh
                geometry={nodes.Torus_2_Mat1_0.geometry}
                material={materials["Mat.1_3"]}
              />
              <mesh
                geometry={nodes.Torus_2_Mat1_0_1.geometry}
                material={materials["Mat.1_4"]}
              />
              <mesh
                geometry={nodes.Torus_2_Mat1_0_2.geometry}
                material={materials["Mat.1_5"]}
              />
            </group>
          </group>
          <group position={[10.484, 12.495, 0]} rotation={[0, 0, Math.PI]}>
            <group position={[1.509, -42.396, 0.564]} rotation={[0.08, 0, 0]}>
              <mesh
                geometry={nodes.Top_torus_Mat1_0.geometry}
                material={materials["Mat.1_6"]}
              />
              <mesh
                geometry={nodes.Top_torus_Mat1_0_1.geometry}
                material={materials["Mat.1_7"]}
              />
              <mesh
                geometry={nodes.Top_torus_Mat1_0_2.geometry}
                material={materials["Mat.1_8"]}
              />
            </group>
            <group position={[1.509, -34.365, 1.212]} rotation={[0.08, 0, 0]}>
              <mesh
                geometry={nodes.Top_torus_2_Mat5_0.geometry}
                material={materials["Mat.5"]}
              />
              <mesh
                geometry={nodes.Top_torus_2_Mat4_0.geometry}
                material={materials["Mat.4"]}
              />
            </group>
            <mesh
              geometry={nodes.Bottom_torus_Mat_0.geometry}
              material={materials.Mat_2}
              position={[1.509, -57.343, 0.906]}
              rotation={[0.137, 0, 0]}
            />
            <mesh
              geometry={nodes.Top_torus_1_Mat_0.geometry}
              material={materials.Mat_3}
              position={[1.509, -49.957, 2.406]}
              rotation={[0.134, 0, 0]}
            />
          </group>
          <group
            position={[10.483, 15.737, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <group position={[0, 34.967, 0]} rotation={[-Math.PI, 0, Math.PI]}>
              <mesh
                geometry={nodes.Cylinder_1_7_Mat1_0.geometry}
                material={materials["Mat.1_10"]}
              />
              <mesh
                geometry={nodes.Cylinder_1_7_Mat1_0_1.geometry}
                material={materials["Mat.1_11"]}
              />
            </group>
            <mesh
              geometry={nodes.Top_Mat1_0.geometry}
              material={materials["Mat.1_9"]}
              position={[0, 9.621, 0]}
            />
            <mesh
              geometry={nodes.Bottom_1_Mat1_0.geometry}
              material={materials["Mat.1_9"]}
              position={[0, 60.536, 0]}
              rotation={[-Math.PI, 0, 0]}
            />
          </group>
          <group position={[9.715, 88.715, 0]} rotation={[0, 0, Math.PI]}>
            <group position={[0.948, -47.039, -34.868]}>
              <group
                position={[-5.552, 6.529, 65.024]}
                rotation={[2.241, 0, 0]}
              >
                <mesh
                  geometry={nodes.Tube_4_Mat_0.geometry}
                  material={materials.Mat_3}
                />
                <mesh
                  geometry={nodes.Tube_4_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
                <mesh
                  geometry={nodes.Tube_4_Mat_0_2.geometry}
                  material={materials.Mat_4}
                />
              </group>
              <mesh
                geometry={nodes.Cube_3_3_Mat5_0.geometry}
                material={materials["Mat.5"]}
                position={[-45.653, 37.926, 34.58]}
              />
              <mesh
                geometry={nodes.Triangle_Mat_0.geometry}
                material={materials.material}
                position={[32.35, 27.387, 20.484]}
                rotation={[0, 0.787, 0]}
              />
              <mesh
                geometry={nodes.Ball_1_Mat5_0.geometry}
                material={materials["Mat.5"]}
                position={[32.096, -7.811, 59.475]}
                rotation={[0.562, 0.325, -0.49]}
              />
              <mesh
                geometry={nodes.Ball_Mat_0.geometry}
                material={materials.Mat_5}
                position={[-9.407, -18.668, 0.579]}
                rotation={[0.562, 0.325, 0.469]}
              />
              <mesh
                geometry={nodes.Game_detail_Mat_0.geometry}
                material={materials.Mat_0}
                position={[9.407, 18.668, -0.579]}
                rotation={[Math.PI / 2, 0.563, 0]}
              />
            </group>
            <group position={[-3.282, -42.207, 0]}>
              <mesh
                geometry={nodes.Cube_1_4_Mat1_0.geometry}
                material={materials["Mat.1_4"]}
              />
              <mesh
                geometry={nodes.Cube_1_4_Mat1_0_1.geometry}
                material={materials["Mat.1_5"]}
              />
              <mesh
                geometry={nodes.Cube_1_4_Mat1_0_2.geometry}
                material={materials["Mat.1_3"]}
              />
              <mesh
                geometry={nodes.Cube_1_4_Mat_0.geometry}
                material={materials.Mat_2}
              />
            </group>
            <mesh
              geometry={nodes.White_base_Mat1_0.geometry}
              material={materials["Mat.1_12"]}
              position={[-3.282, -87.96, -0.187]}
            />
          </group>
        </group>
        <group position={[51.073, -28.855, 72.176]}>
          <group position={[0, 114.521, 0]}>
            <mesh
              geometry={nodes.Cylinder_4_5_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
            />
            <mesh
              geometry={nodes.Cylinder_4_5_Mat2_0.geometry}
              material={materials["Mat.2"]}
            />
          </group>
          <group position={[3.485, 55.709, -0.288]}>
            <mesh
              geometry={nodes.Cylinder_8_Mat1_0.geometry}
              material={materials["Mat.1_4"]}
              position={[10.719, 0, -23.229]}
            />
            <mesh
              geometry={nodes.Cylinder_9_Mat1_0.geometry}
              material={materials["Mat.1_4"]}
              position={[-7.567, 0, -27.549]}
            />
            <mesh
              geometry={nodes.Cylinder_10_Mat1_0.geometry}
              material={materials["Mat.1_5"]}
              position={[-26.861, 0, -15.454]}
            />
            <mesh
              geometry={nodes.Cylinder_11_Mat1_0.geometry}
              material={materials["Mat.1_4"]}
              position={[-29.74, 0, 5.567]}
            />
            <mesh
              geometry={nodes.Cylinder_12_Mat1_0.geometry}
              material={materials["Mat.1_11"]}
              position={[-17.502, 0, 24.573]}
            />
            <mesh
              geometry={nodes.Cylinder_13_Mat1_0.geometry}
              material={materials["Mat.1_3"]}
              position={[2.944, 0, 27.741]}
            />
            <mesh
              geometry={nodes.Cylinder_7_Mat1_0.geometry}
              material={materials["Mat.1_3"]}
              position={[24.253, 0, -4.079]}
            />
            <mesh
              geometry={nodes.Cylinder_2_8_Mat1_0.geometry}
              material={materials["Mat.1_4"]}
              position={[19.502, 0, 16.51]}
            />
            <mesh
              geometry={nodes.Cylinder_7_2_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
              position={[-2.757, 82.437, 0.422]}
            />
          </group>
          <group position={[0, -2.949, 0]}>
            <mesh
              geometry={nodes.Cylinder_8_2_Mat5_0.geometry}
              material={materials["Mat.5"]}
            />
            <mesh
              geometry={nodes.Cylinder_8_2_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
          </group>
          <mesh
            geometry={nodes.Sphere_2_5_Mat_0.geometry}
            material={materials.Mat_3}
            position={[0.632, 49.238, 5.964]}
          />
          <mesh
            geometry={nodes.Sphere_6_Mat3_0.geometry}
            material={materials["Mat.3"]}
            position={[0.632, 21.218, -2.587]}
          />
          <mesh
            geometry={nodes.Sphere_1_7_Mat4_0.geometry}
            material={materials["Mat.4"]}
            position={[0.632, 157.994, 0.077]}
          />
        </group>
        <group position={[76.118, -45.202, -45.122]}>
          <group position={[0, 20.989, -113.557]}>
            <mesh
              geometry={nodes.Cube_1_5_Mat_0.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.Cube_1_5_Mat_0_1.geometry}
              material={materials.Mat_5}
            />
          </group>
          <mesh
            geometry={nodes.Cube_5_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[0, 4.579, -113.557]}
          />
        </group>
        <group position={[-164.481, -34.007, -83.005]} rotation={[0, 0.787, 0]}>
          <mesh
            geometry={nodes.Cylinder_9_2_Mat5_0.geometry}
            material={materials["Mat.5"]}
            position={[0, 15.108, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_7_3_Mat_0.geometry}
            material={materials.material}
            position={[0, 0.456, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_1_8_Mat1_0.geometry}
            material={materials["Mat.1_7"]}
            position={[0, 29.632, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_2_9_Mat_0.geometry}
            material={materials.Mat_6}
            position={[0, 44.43, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_3_8_Mat1_0.geometry}
            material={materials["Mat.1_4"]}
            position={[0, 59.096, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_4_6_Mat_0.geometry}
            material={materials.Mat_7}
            position={[0, 73.737, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_5_2_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[0, -7.121, 0]}
          />
          <mesh
            geometry={nodes.Capsule_1_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[0, 72.616, 0]}
          />
        </group>
        <group position={[-59.554, -45.202, 103.981]}>
          <group
            position={[-1.948, 65.202, -80.111]}
            rotation={[Math.PI / 2, 0, -0.262]}
          >
            <mesh
              geometry={nodes.Cylinder_10_2_Mat_0.geometry}
              material={materials.Mat_3}
            />
            <mesh
              geometry={nodes.Cylinder_10_2_Mat_0_1.geometry}
              material={materials.Mat_0}
            />
          </group>
          <group
            position={[-1.948, 65.202, -72.679]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Tube_4_2_Mat_0.geometry}
              material={materials.Mat_5}
            />
            <mesh
              geometry={nodes.Tube_4_2_Mat_0_1.geometry}
              material={materials.Mat_8}
            />
          </group>
          <group
            position={[-1.948, 65.202, -72.679]}
            rotation={[Math.PI / 2, 0, 0.075]}
          >
            <mesh
              geometry={nodes.Tube_3_2_Mat_0.geometry}
              material={materials.Mat_9}
            />
            <mesh
              geometry={nodes.Tube_3_2_Mat_0_1.geometry}
              material={materials.Mat_7}
            />
          </group>
          <group
            position={[-2.346, 65.202, -70.587]}
            rotation={[Math.PI / 2, 0, 0.188]}
          >
            <mesh
              geometry={nodes.Tube_2_6_Mat1_0.geometry}
              material={materials["Mat.1_13"]}
            />
            <mesh
              geometry={nodes.Tube_2_6_Mat1_0_1.geometry}
              material={materials["Mat.1_5"]}
            />
          </group>
          <group
            position={[-2.754, 65.202, -63.155]}
            rotation={[Math.PI / 2, 0, 0.084]}
          >
            <mesh
              geometry={nodes.Tube_1_4_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
            />
            <mesh
              geometry={nodes.Tube_1_4_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
            <mesh
              geometry={nodes.Tube_1_4_Mat2_0.geometry}
              material={materials["Mat.2"]}
            />
          </group>
          <group
            position={[-2.459, 65.202, -67.719]}
            rotation={[Math.PI / 2, 0, 0.103]}
          >
            <mesh
              geometry={nodes.Tube_5_2_Mat2_0.geometry}
              material={materials["Mat.2"]}
            />
            <mesh
              geometry={nodes.Tube_5_2_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
            <mesh
              geometry={nodes.Tube_5_2_Mat2_0_1.geometry}
              material={materials["Mat.2_0"]}
            />
            <mesh
              geometry={nodes.Tube_5_2_Mat2_0_2.geometry}
              material={materials["Mat.2_1"]}
            />
          </group>
          <group position={[-6.5, 33.657, -88.9]} rotation={[0, 0.787, 0]}>
            <mesh
              geometry={nodes.Base_1_Mat1_0.geometry}
              material={materials["Mat.1_5"]}
            />
            <mesh
              geometry={nodes.Base_1_Mat_0.geometry}
              material={materials.Mat_10}
            />
            <mesh
              geometry={nodes.Base_1_Mat_0_1.geometry}
              material={materials.Mat_2}
            />
            <mesh
              geometry={nodes.Base_1_Mat1_0_1.geometry}
              material={materials["Mat.1_4"]}
            />
            <mesh
              geometry={nodes.Base_1_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
            <mesh
              geometry={nodes.Base_1_Mat5_0.geometry}
              material={materials["Mat.5"]}
            />
          </group>
          <mesh
            geometry={nodes.Tube_5_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[-1.88, 65.202, -76.408]}
            rotation={[Math.PI / 2, 0, -0.261]}
          />
        </group>
        <group position={[-202.673, 4.304, 78.782]} rotation={[0, 0.787, 0]}>
          <group position={[0, 76.804, -10.212]}>
            <mesh
              geometry={nodes.Cube_2_5_Mat5_0.geometry}
              material={materials["Mat.5"]}
            />
            <mesh
              geometry={nodes.Cube_2_5_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
          </group>
          <group position={[30.357, 71.529, 24.747]}>
            <mesh
              geometry={nodes.Cylinder_1_9_Mat_0.geometry}
              material={materials.Mat_5}
            />
            <mesh
              geometry={nodes.Cylinder_1_9_Mat_0_1.geometry}
              material={materials.Mat_6}
            />
          </group>
          <group position={[-31.913, 56.922, -32.208]}>
            <mesh
              geometry={nodes.Cube_3_4_Mat_0.geometry}
              material={materials.Mat_11}
            />
            <mesh
              geometry={nodes.Cube_3_4_Mat_0_1.geometry}
              material={materials.Mat_3}
            />
          </group>
          <group position={[0, 2.168, 0]}>
            <mesh
              geometry={nodes.Base_Mat1_0.geometry}
              material={materials["Mat.1_10"]}
            />
            <mesh
              geometry={nodes.Base_Mat1_0_1.geometry}
              material={materials["Mat.1_3"]}
            />
            <mesh
              geometry={nodes.Base_Mat1_0_2.geometry}
              material={materials["Mat.1_14"]}
            />
            <mesh
              geometry={nodes.Base_Mat_0.geometry}
              material={materials.Mat_7}
            />
            <mesh
              geometry={nodes.Base_Mat5_0.geometry}
              material={materials["Mat.5"]}
            />
            <mesh
              geometry={nodes.Base_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
          </group>
          <group position={[35.043, -22.964, -55.48]}>
            <mesh
              geometry={nodes.Cube_4_2_Mat5_0.geometry}
              material={materials["Mat.5"]}
            />
            <mesh
              geometry={nodes.Cube_4_2_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
            />
          </group>
          <group position={[-58.396, -36.81, 95.738]} rotation={[0, 0.766, 0]}>
            <mesh
              geometry={nodes.Cube_7_Mat_0.geometry}
              material={materials.Mat_7}
            />
            <mesh
              geometry={nodes.Cube_7_Mat_0_1.geometry}
              material={materials.Mat_12}
            />
          </group>
          <group
            position={[-128.149, -29.575, 22.762]}
            rotation={[0, -0.227, 0]}
          >
            <mesh
              geometry={nodes.Cube_8_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
            <mesh
              geometry={nodes.Cube_8_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
            />
          </group>
          <group position={[-30.796, 16.719, -57.668]} rotation={[0, 0.766, 0]}>
            <mesh
              geometry={nodes.Cube_10_Mat_0.geometry}
              material={materials.Mat_6}
            />
            <mesh
              geometry={nodes.Cube_10_Mat_0_1.geometry}
              material={materials.Mat_5}
            />
          </group>
          <group
            position={[-20.869, -14.202, -62.18]}
            rotation={[0, 0.766, -0.592]}
          >
            <mesh
              geometry={nodes.Cube_11_Mat_0.geometry}
              material={materials.Mat_13}
            />
            <mesh
              geometry={nodes.Cube_11_Mat_0_1.geometry}
              material={materials.Mat_11}
            />
          </group>
          <group position={[55.47, 28.249, -23.682]}>
            <mesh
              geometry={nodes.Cube_12_Mat1_0.geometry}
              material={materials["Mat.1_5"]}
            />
            <mesh
              geometry={nodes.Cube_12_Mat1_0_1.geometry}
              material={materials["Mat.1_4"]}
            />
          </group>
          <mesh
            geometry={nodes.Cylinder_11_2_Mat_0.geometry}
            material={materials.material}
            position={[30.357, 55.344, 26.643]}
          />
          <mesh
            geometry={nodes.Cube_1_6_Mat_0.geometry}
            material={materials.Mat_3}
            position={[3.349, 57.054, -20.61]}
          />
          <mesh
            geometry={nodes.Cube_6_Mat1_0.geometry}
            material={materials["Mat.1_5"]}
            position={[0, 57.054, 0]}
          />
          <mesh
            geometry={nodes.Cube_5_2_Mat1_0.geometry}
            material={materials["Mat.1_3"]}
            position={[-51.772, -37.14, -79.49]}
            rotation={[0, 0.766, 0]}
          />
          <mesh
            geometry={nodes.Base_1_2_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[0, -45.077, 0]}
          />
          <mesh
            geometry={nodes.Cube_6_2_Mat_0.geometry}
            material={materials.Mat_3}
            position={[72.578, -37.14, -65.249]}
            rotation={[0, 0.766, 0]}
          />
          <mesh
            geometry={nodes.Cube_9_Mat1_0.geometry}
            material={materials["Mat.1_11"]}
            position={[-35.86, -33.92, 67.996]}
            rotation={[0, 1.284, 0.24]}
          />
          <mesh
            geometry={nodes.Cylinder_2_10_Mat_0.geometry}
            material={materials.Mat_12}
            position={[-15.145, 9.123, 61.037]}
            rotation={[0, 0, 0.603]}
          />
        </group>
        {/* 小车 */}
        <group
          position={[156.957, -10.295, -247.742]}
          rotation={[0, -0.554, 0]}
        >
          <group position={[-4.191, 12.786, -1.151]}>
            <mesh
              geometry={nodes.Violet_Triangle_Mat_0.geometry}
              material={materials.Mat_0}
            />
            <mesh
              geometry={nodes.Violet_Triangle_Mat_0_1.geometry}
              material={materials.Mat_13}
            />
          </group>
          <group
            position={[26.117, 5.101, -1.151]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes.Orange_triangle_Mat4_0.geometry}
              material={materials["Mat.4"]}
            />
            <mesh
              geometry={nodes.Orange_triangle_Mat3_0.geometry}
              material={materials["Mat.3_0"]}
            />
          </group>
          <group position={[-18.418, -19.463, -1.151]}>
            <mesh
              geometry={nodes.Ship_base_Mat1_0.geometry}
              material={materials["Mat.1_13"]}
            />
            <mesh
              geometry={nodes.Ship_base_Mat1_0_1.geometry}
              material={materials["Mat.1_5"]}
            />
          </group>
          <group
            position={[-17.039, -23.276, 7.465]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-24.342, 0, 0.056]}>
              <group
                position={[-0.059, -6.542, 0.07]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_detail_Mat4_0.geometry}
                  material={materials["Mat.4"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_Mat5_0.geometry}
                  material={materials["Mat.5"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_Mat3_0.geometry}
                  material={materials["Mat.3_0"]}
                />
              </group>
              <group
                position={[0.059, -1.995, -0.07]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_Mat1_0.geometry}
                  material={materials["Mat.1_3"]}
                />
                <mesh
                  geometry={nodes.Wheel_Mat1_0_1.geometry}
                  material={materials["Mat.1_14"]}
                />
                <mesh
                  geometry={nodes.Wheel_Mat1_0_2.geometry}
                  material={materials["Mat.1_4"]}
                />
              </group>
            </group>
            <group position={[24.342, 0, -0.056]}>
              <group
                position={[-0.005, -6.016, -0.043]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_detail_1_Mat_0.geometry}
                  material={materials.Mat_3}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_Mat_0_2.geometry}
                  material={materials.Mat_11}
                />
              </group>
              <group
                position={[0.005, -2.077, 0.043]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_1_Mat1_0.geometry}
                  material={materials["Mat.1_3"]}
                />
                <mesh
                  geometry={nodes.Wheel_1_Mat1_0_1.geometry}
                  material={materials["Mat.1_14"]}
                />
                <mesh
                  geometry={nodes.Wheel_1_Mat1_0_2.geometry}
                  material={materials["Mat.1_4"]}
                />
              </group>
            </group>
          </group>
          <group
            position={[-17.039, -23.276, -13.807]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-24.342, 0, 0.056]}>
              <group position={[-0.059, 1.942, 0.07]}>
                <mesh
                  geometry={nodes.Wheel_detail_2_Mat4_0.geometry}
                  material={materials["Mat.4"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_2_Mat5_0.geometry}
                  material={materials["Mat.5"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_2_Mat3_0.geometry}
                  material={materials["Mat.3_0"]}
                />
              </group>
              <group position={[0.059, -1.995, -0.07]}>
                <mesh
                  geometry={nodes.Wheel_2_Mat1_0.geometry}
                  material={materials["Mat.1_3"]}
                />
                <mesh
                  geometry={nodes.Wheel_2_Mat1_0_1.geometry}
                  material={materials["Mat.1_14"]}
                />
                <mesh
                  geometry={nodes.Wheel_2_Mat1_0_2.geometry}
                  material={materials["Mat.1_4"]}
                />
              </group>
            </group>
            <group position={[24.342, 0, -0.056]}>
              <group position={[-0.005, 1.995, -0.043]}>
                <mesh
                  geometry={nodes.Wheel_detail_1_2_Mat_0.geometry}
                  material={materials.Mat_3}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_2_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_2_Mat_0_2.geometry}
                  material={materials.Mat_11}
                />
              </group>
              <group position={[0.005, -1.995, 0.043]}>
                <mesh
                  geometry={nodes.Wheel_1_2_Mat1_0.geometry}
                  material={materials["Mat.1_3"]}
                />
                <mesh
                  geometry={nodes.Wheel_1_2_Mat1_0_1.geometry}
                  material={materials["Mat.1_14"]}
                />
                <mesh
                  geometry={nodes.Wheel_1_2_Mat1_0_2.geometry}
                  material={materials["Mat.1_4"]}
                />
              </group>
            </group>
          </group>
        </group>
        <group
          position={[-50.909, -10.295, 293.087]}
          rotation={[Math.PI, -0.615, Math.PI]}
        >
          <group position={[-4.191, 12.786, -1.151]}>
            <mesh
              geometry={nodes.Violet_Triangle_2_Mat1_0.geometry}
              material={materials["Mat.1_13"]}
            />
            <mesh
              geometry={nodes.Violet_Triangle_2_Mat1_0_1.geometry}
              material={materials["Mat.1_4"]}
            />
          </group>
          <group
            position={[26.117, 5.101, -1.151]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes.Orange_triangle_2_Mat1_0.geometry}
              material={materials["Mat.1_3"]}
            />
            <mesh
              geometry={nodes.Orange_triangle_2_Mat1_0_1.geometry}
              material={materials["Mat.1_14"]}
            />
          </group>
          <group position={[-18.418, -19.463, -1.151]}>
            <mesh
              geometry={nodes.Ship_base_2_Mat_0.geometry}
              material={materials.Mat_9}
            />
            <mesh
              geometry={nodes.Ship_base_2_Mat_0_1.geometry}
              material={materials.Mat_7}
            />
          </group>
          <group
            position={[-17.039, -23.276, 7.465]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-24.342, 0, 0.056]}>
              <group
                position={[-0.059, -6.542, 0.07]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_detail_3_Mat4_0.geometry}
                  material={materials["Mat.4"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_3_Mat5_0.geometry}
                  material={materials["Mat.5"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_3_Mat3_0.geometry}
                  material={materials["Mat.3_0"]}
                />
              </group>
              <mesh
                geometry={nodes.Wheel_3_Mat_0.geometry}
                material={materials.Mat_10}
                position={[0.059, -1.995, -0.07]}
                rotation={[0, 0, Math.PI]}
              />
            </group>
            <group position={[24.342, 0, -0.056]}>
              <group
                position={[-0.005, -6.016, -0.043]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  geometry={nodes.Wheel_detail_1_3_Mat_0.geometry}
                  material={materials.Mat_3}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_3_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_3_Mat_0_2.geometry}
                  material={materials.Mat_11}
                />
              </group>
              <mesh
                geometry={nodes.Wheel_1_3_Mat_0.geometry}
                material={materials.Mat_10}
                position={[0.005, -2.077, 0.043]}
                rotation={[0, 0, Math.PI]}
              />
            </group>
          </group>
          <group
            position={[-17.039, -23.276, -13.807]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[-24.342, 0, 0.056]}>
              <group position={[-0.059, 1.942, 0.07]}>
                <mesh
                  geometry={nodes.Wheel_detail_4_Mat4_0.geometry}
                  material={materials["Mat.4"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_4_Mat5_0.geometry}
                  material={materials["Mat.5"]}
                />
                <mesh
                  geometry={nodes.Wheel_detail_4_Mat3_0.geometry}
                  material={materials["Mat.3_0"]}
                />
              </group>
              <mesh
                geometry={nodes.Wheel_4_Mat_0.geometry}
                material={materials.Mat_2}
                position={[0.059, -1.995, -0.07]}
              />
            </group>
            <group position={[24.342, 0, -0.056]}>
              <group position={[-0.005, 1.995, -0.043]}>
                <mesh
                  geometry={nodes.Wheel_detail_1_4_Mat_0.geometry}
                  material={materials.Mat_3}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_4_Mat_0_1.geometry}
                  material={materials.Mat_0}
                />
                <mesh
                  geometry={nodes.Wheel_detail_1_4_Mat_0_2.geometry}
                  material={materials.Mat_11}
                />
              </group>
              <mesh
                geometry={nodes.Wheel_1_4_Mat_0.geometry}
                material={materials.Mat_2}
                position={[0.005, -1.995, 0.043]}
              />
            </group>
          </group>
        </group>
        <group position={[70.826, 13.592, -45.122]}>
          <group position={[5.292, -29.315, 0]}>
            <group position={[0, 37.066, 0]}>
              <mesh
                geometry={nodes.Cylinder_3_10_Mat1_0.geometry}
                material={materials["Mat.1_4"]}
              />
              <mesh
                geometry={nodes.Cylinder_3_10_Mat1_0_1.geometry}
                material={materials["Mat.1_11"]}
              />
              <mesh
                geometry={nodes.Cylinder_3_10_Mat1_0_2.geometry}
                material={materials["Mat.1_3"]}
              />
            </group>
            <group position={[0, -3.113, 0]}>
              <mesh
                geometry={nodes.Cylinder_4_7_Mat1_0.geometry}
                material={materials["Mat.1_5"]}
              />
              <mesh
                geometry={nodes.Cylinder_4_7_Mat_0.geometry}
                material={materials.Mat_10}
              />
              <mesh
                geometry={nodes.Cylinder_4_7_Mat_0_1.geometry}
                material={materials.Mat_2}
              />
              <mesh
                geometry={nodes.Cylinder_4_7_Mat1_0_1.geometry}
                material={materials["Mat.1_13"]}
              />
            </group>
            <group position={[1.868, 52.016, 21.8]}>
              <mesh
                geometry={nodes.Cylinder_13_2_Mat_0.geometry}
                material={materials.Mat_5}
              />
              <mesh
                geometry={nodes.Cylinder_13_2_Mat_0_1.geometry}
                material={materials.material}
              />
            </group>
            <mesh
              geometry={nodes.Cylinder_1_11_Mat_0.geometry}
              material={materials.Mat_0}
              position={[0, 25.555, 0]}
            />
          </group>
          <mesh
            geometry={nodes.Star_Mat3_0.geometry}
            material={materials["Mat.3"]}
            position={[-110.793, -54.983, -70.722]}
          />
          {/*  杆子 向左移动 90 度 然后回来 */}

          <mesh
            geometry={nodes.Cylinder_3_9_Mat1_0.geometry}
            material={materials["Mat.1_14"]}
            position={[-11.851, 36.02, -6.99]}
            rotation={[-Math.PI / 2, 0, -0.788]}
          />
          <mesh
            geometry={nodes.Connect_Mat1_0.geometry}
            material={materials["Mat.1_12"]}
            position={[7.135, -58.793, -0.921]}
          />
          <mesh
            geometry={nodes.Capsule_1_2_Mat1_0.geometry}
            material={materials["Mat.1_11"]}
            position={[-75.57, 35.809, -64.155]}
            rotation={[-Math.PI / 2, 0, 0.787]}
          />
          <mesh
            geometry={nodes.Cylinder_2_11_Mat3_0.geometry}
            material={materials["Mat.3"]}
            position={[-63.934, -51.295, -61.156]}
            rotation={[-Math.PI, -0.787, 0]}
          />
          <mesh
            geometry={nodes.Cube_7_2_Mat_0.geometry}
            material={materials.Mat_0}
            position={[29.008, 35.687, 40.061]}
            rotation={[0, -0.784, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Cylinder_12_2_Mat4_0.geometry}
            material={materials["Mat.4"]}
            position={[15.844, 36.687, 17.533]}
            rotation={[-Math.PI / 2, 0, -0.788]}
          />
          <mesh
            geometry={nodes.Cylinder_1_10_Mat4_0.geometry}
            material={materials["Mat.4"]}
            position={[17.71, 36.687, 10.32]}
            rotation={[-Math.PI / 2, 0, -0.788]}
          />
          <mesh
            geometry={nodes.Cylinder_4_8_Mat1_0.geometry}
            material={materials["Mat.1_14"]}
            position={[-44.762, 35.898, -40.084]}
            rotation={[-Math.PI / 2, 0, -0.788]}
          />
          <mesh
            geometry={nodes.Cylinder_5_3_Mat1_0.geometry}
            material={materials["Mat.1_14"]}
            position={[-78.409, 35.4, -73.919]}
            rotation={[-Math.PI / 2, 0, -0.788]}
          />
          {/* 杆子结束 */}
        </group>
        <group position={[-18.693, -40.404, -15.471]}>
          <mesh
            geometry={nodes.Cube_8_2_Mat_0.geometry}
            material={materials.Mat_2}
            position={[-10.985, -1.936, -118.057]}
            rotation={[0, 0.395, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_11_3_Mat_0.geometry}
            material={materials.Mat_14}
            position={[289.016, 0.786, 176.722]}
            rotation={[0, 1.374, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_10_3_Mat_0.geometry}
            material={materials.Mat_5}
            position={[407.473, 3.96, -235.998]}
            rotation={[0, 1.374, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_9_3_Mat_0.geometry}
            material={materials.Mat_7}
            position={[414.283, -3.324, 132.896]}
            rotation={[Math.PI, -0.791, Math.PI]}
          />
          <mesh
            geometry={nodes.Cylinder_7_4_Mat_0.geometry}
            material={materials.Mat_12}
            position={[69.149, -3.926, 77.051]}
            rotation={[0, 0.398, 0]}
          />
          <mesh
            geometry={nodes.Cube_1_7_Mat_0.geometry}
            material={materials.material}
            position={[-401.471, -4.005, -278.405]}
            rotation={[0, 0.395, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_6_2_Mat_0.geometry}
            material={materials.Mat_2}
            position={[-370.41, 2.229, -257.153]}
            rotation={[0, 1.374, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_2_13_Mat_0.geometry}
            material={materials.material}
            position={[-121.511, -3.346, 387.36]}
            rotation={[Math.PI, -0.791, Math.PI]}
          />
          <mesh
            geometry={nodes.Cylinder_5_4_Mat_0.geometry}
            material={materials.Mat_7}
            position={[-286.528, -3.635, -2.473]}
            rotation={[Math.PI, 1.567, -Math.PI]}
          />
          <mesh
            geometry={nodes.Cylinder_1_12_Mat_0.geometry}
            material={materials.Mat_12}
            position={[-125.605, -3.834, -394.498]}
            rotation={[0, 0.787, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_3_11_Mat_0.geometry}
            material={materials.Mat_14}
            position={[269.16, -4.042, -231.968]}
            rotation={[Math.PI, 1.569, -Math.PI]}
          />
          <mesh
            geometry={nodes.Base_3_Mat_0.geometry}
            material={materials.Mat_10}
            position={[-44.398, -6.393, 33.504]}
            rotation={[0, 0.787, 0]}
          />
          <mesh
            geometry={nodes.Cylinder_14_Mat_0.geometry}
            material={materials.Mat_9}
            position={[-481.271, -0.37, 299.615]}
            rotation={[0, 1.374, 0]}
          />
        </group>
      </group>
    </a.group>
  );
}
